### ISSUE TITLE
Code error due to xsize

### ISSUE THREAD

**Issue by dcurtis-uofu** [leojahrens/fedistr#1]
Thanks for this new package! 

When trying to run the code across different datasets and using various command options, I kept getting the following error: xsize must be between 1.000 and 20.000.  Any ideas for how to resolve?

**Comment by leojahrens** [comment]
Thanks! 
What exact command produces this error? 
In my version of Stata, xsize can be between 1 and 100. What version of Stata are you using? Can you try this command (with x and y variables of your choice) and tell me what happens? 
scatter y x, xsize(100)

**Comment by dcurtis-uofu** [comment]
Any of the commands using fedistr return this error, even the examples from
the help file (eg: fedistr gnppc, fe(region)).
I tried the suggested command and it returned the same error (i.e., xsize
must be between 1.000 and 20.000). So, maybe it is due to a limitation of
an earlier version of Stata, as I am using Stata/IC 15.1.

**Comment by leojahrens** [comment]
Thanks for making me aware. I coded up the solution already. But I want to implement other changes as well so this might take up to a week. I'll send you a message when the new version is up. I can also send you a few lines of code if you want to edit the .ado file yourself, the solution is simple.

**Comment by dcurtis-uofu** [comment]
Thanks for your prompt response.  I will wait until the updated .ado file
is posted.  Looking forward to using the new program.

**Comment by leojahrens** [comment]
The new version is online. Please report back if your issue is resolved after updating.
